require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout:
  Enabled: false

Metrics:
  Enabled: false


Style/CommentedKeyword:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/Documentation:
  Enabled: false


Bundler/OrderedGems:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
